name: Release and Deploy

on:
  push:
    branches:
      - main

jobs:
  release-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code
    - name: Checkout Code
      uses: actions/checkout@v4

    # Package the application
    - name: Package Application
      run: zip -r release.zip ./*

    # Validate the package
    - name: Verify Release Package
      run: ls -lh release.zip

    # Install AWS CLI
    - name: Install AWS CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y awscli

    # Configure AWS CLI
    - name: Configure AWS CLI
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
      run: |
        aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
        aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
        aws configure set region $AWS_REGION

    # Extract and install dependencies
    - name: Unzip Release Package
      run: unzip release.zip -d app/

    - name: Install Dependencies
      working-directory: ./app
      run: npm install --only=prod

    # Repackage Lambda Deployment Package
    - name: Repackage Lambda Deployment Package
      working-directory: ./app
      run: zip -r lambda-deploy.zip ./*

    # Deploy to AWS Lambda
    - name: Deploy to AWS Lambda
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
      run: |
        aws lambda update-function-code \
          --function-name KyleWilkins_NodeApp \
          --zip-file fileb://app/lambda-deploy.zip
