name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Package Application
      run: zip -r release.zip ./*

    - name: Verify Release Package
      run: ls -lh release.zip
    
    - name: Upload Release Artifact
      uses: actions/upload-artifact@v3
      with:
        name: release-artifact
        path: release.zip
